id: P01376FCA
initial_creation_type: ocr
source_metadata:
  volumes:
    6ac83c12078b4d01bc274eed91d3fe73:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: སྦྱིན་སྲེག་གི་ཆོ་ག།
      total_pages: 1734
      volume_number: 34
